# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logregs', '0003_auto_20170922_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs_sent', to='logregs.Users')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs_received', to='logregs.Users')),
            ],
        ),
    ]
