# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logregs', '0002_users_access_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
